# Generated by Django 5.1.2 on 2024-11-17 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("candidates", "0004_alter_candidateapplicationdata_dhp_note_and_more"),
        ("utilities", "0004_alter_historicalinstitution_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Job Title")),
                ("description", models.TextField(verbose_name="Job Description")),
                (
                    "minimum_experience_years",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Minimum Years of Experience"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "candidates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="jobs",
                        to="candidates.candidate",
                        verbose_name="Chosen Candidates",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="utilities.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "field_of_study",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="utilities.fieldofstudy",
                        verbose_name="Field of Study",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="utilities.country",
                        verbose_name="Job Location",
                    ),
                ),
                (
                    "required_degree",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="utilities.degreechoices",
                        verbose_name="Required Degree",
                    ),
                ),
                (
                    "required_languages",
                    models.ManyToManyField(
                        blank=True,
                        to="utilities.languagechoices",
                        verbose_name="Required Languages",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job",
                "verbose_name_plural": "Jobs",
                "ordering": ["-created_at"],
            },
        ),
    ]
