# Generated by Django 5.1.2 on 2024-11-18 10:18

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0004_alter_candidateapplicationdata_dhp_note_and_more"),
        ("jobs", "0001_initial"),
        ("utilities", "0004_alter_historicalinstitution_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalJobOpportunity",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=255, verbose_name="Job Title"),
                ),
                ("job_description", models.TextField(verbose_name="Job Description")),
                (
                    "minimum_years_of_experience",
                    models.PositiveIntegerField(
                        verbose_name="Minimum Years of Experience"
                    ),
                ),
                (
                    "minimum_age",
                    models.PositiveIntegerField(verbose_name="Minimum Age"),
                ),
                (
                    "maximum_age",
                    models.PositiveIntegerField(verbose_name="Maximum Age"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("Any", "Any")],
                        max_length=3,
                        verbose_name="Gender",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="utilities.institution",
                        verbose_name="Institution",
                    ),
                ),
                (
                    "job_department",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="utilities.department",
                        verbose_name="Job Department",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Job Opportunity",
                "verbose_name_plural": "historical Job Opportunities",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="JobOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_title",
                    models.CharField(max_length=255, verbose_name="Job Title"),
                ),
                ("job_description", models.TextField(verbose_name="Job Description")),
                (
                    "minimum_years_of_experience",
                    models.PositiveIntegerField(
                        verbose_name="Minimum Years of Experience"
                    ),
                ),
                (
                    "minimum_age",
                    models.PositiveIntegerField(verbose_name="Minimum Age"),
                ),
                (
                    "maximum_age",
                    models.PositiveIntegerField(verbose_name="Maximum Age"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("Any", "Any")],
                        max_length=3,
                        verbose_name="Gender",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_degrees",
                    models.ManyToManyField(
                        to="utilities.degreechoices", verbose_name="Accepted Degrees"
                    ),
                ),
                (
                    "candidates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="job_opportunities",
                        to="candidates.candidate",
                        verbose_name="Candidates",
                    ),
                ),
                (
                    "fields_of_study",
                    models.ManyToManyField(
                        to="utilities.fieldofstudy", verbose_name="Fields of Study"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="utilities.institution",
                        verbose_name="Institution",
                    ),
                ),
                (
                    "job_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="utilities.department",
                        verbose_name="Job Department",
                    ),
                ),
                (
                    "nationalities",
                    models.ManyToManyField(
                        to="utilities.nationality", verbose_name="Nationalities"
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Opportunity",
                "verbose_name_plural": "Job Opportunities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Job",
        ),
    ]
