# Generated by Django 5.1.2 on 2024-11-18 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_historicaljobopportunity_jobopportunity_delete_job"),
        ("utilities", "0004_alter_historicalinstitution_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljobopportunity",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="jobopportunity",
            name="institution",
        ),
        migrations.AddField(
            model_name="historicaljobopportunity",
            name="company_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Company Name"
            ),
        ),
        migrations.AddField(
            model_name="jobopportunity",
            name="company_name",
            field=models.CharField(
                default="", max_length=255, verbose_name="Company Name"
            ),
        ),
        migrations.AddField(
            model_name="jobopportunity",
            name="departments",
            field=models.ManyToManyField(
                help_text="Select departments that the candidate should have experience in.",
                related_name="job_opportunities_as_required",
                to="utilities.department",
                verbose_name="Required Experience Departments",
            ),
        ),
        migrations.AlterField(
            model_name="jobopportunity",
            name="job_department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="job_opportunities_as_department",
                to="utilities.department",
                verbose_name="Job Department",
            ),
        ),
    ]
