# Generated by Django 5.1.2 on 2024-11-06 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidateapplicationdata",
            old_name="MedicalTest_fit_to_work",
            new_name="MedicalTest_is_fit_to_work",
        ),
        migrations.RenameField(
            model_name="historicalcandidateapplicationdata",
            old_name="MedicalTest_fit_to_work",
            new_name="MedicalTest_is_fit_to_work",
        ),
    ]
