# Generated by Django 5.1.3 on 2024-11-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0004_alter_candidateapplicationdata_dhp_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidateapplicationdata",
            name="is_Candidate_Start_Work",
            field=models.BooleanField(
                default=False,
                help_text="Is the candidate starting work?",
                verbose_name="Is Candidate Start Work?",
            ),
        ),
        migrations.AddField(
            model_name="historicalcandidateapplicationdata",
            name="is_Candidate_Start_Work",
            field=models.BooleanField(
                default=False,
                help_text="Is the candidate starting work?",
                verbose_name="Is Candidate Start Work?",
            ),
        ),
    ]
