# Generated by Django 5.1.2 on 2024-11-05 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Enter the name of the license provider.",
                        max_length=255,
                        unique=True,
                        verbose_name="License Provider",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="Select the country where the license provider is located.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="utilities.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "License Provider",
                "verbose_name_plural": "License Providers",
                "ordering": ["name"],
            },
        ),
    ]
