# Generated by Django 5.1.2 on 2024-11-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0003_alter_department_abbreviation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalinstitution",
            name="type",
            field=models.CharField(
                choices=[("University", "University"), ("College", "college")],
                help_text="Enter the type of institution.",
                max_length=255,
                verbose_name="Institution Type",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="type",
            field=models.CharField(
                choices=[("University", "University"), ("College", "college")],
                help_text="Enter the type of institution.",
                max_length=255,
                verbose_name="Institution Type",
            ),
        ),
    ]
